project_id = "ofuldlvfnryrdjrsmyjg"

[functions.assign-teacher-role]
verify_jwt = false

[functions.send-claim-approved-email]
verify_jwt = false

[functions.send-info-response-email]
verify_jwt = false
